# Generated by Django 5.0.6 on 2024-07-30 07:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='organization',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_photos/'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_photos/')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('wallet', models.FloatField(default=0.0)),
                ('history', models.JSONField(blank=True)),
                ('organization', models.ManyToManyField(related_name='orgs', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='socios', to='organizations.person'),
        ),
        migrations.AddField(
            model_name='organization',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='trabajadores', to='organizations.person'),
        ),
    ]
